namespace Common;

public enum WeaponType
{
    None,
    Dagger,
    Sword,
    FireWand,
    Spear,
    Knife,
    Machete,
    FireCharm,
    FireStaff,
    Crossbow,
    Shortbow,
    Longbow,
    Scythe,
    SporeBlaster,
    Flail,
    DoubleDagger,
    TripleDagger,
    Longsword,
    DoubleCrossbow,
    DoubleSpear,
    QuadSpear,
    WarHammer,
    DoubleScythe,
    EnchantedScythe,
    AdvancedSporeBlaster,
    EvolvedSporeBlaster,
    Scimitar,
    DoubleFlail,
    EnchantedFlail,
    SplitLongbow,
    TripleCrossbow
}